/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author aarti
 */
public class patient extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    int supid;
    int ptid;
    int pno;
    public patient() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
            Statement stmt = conn.createStatement();
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
            Statement ps1 = conn.createStatement();
                    
            
             
            ResultSet rs=ps1.executeQuery(" select max(pid) from patient");
            int cnt=0;
            while(rs.next())
            {
              
                cnt=rs.getInt(1);
            }
            cnt++;
            pidtext.setText(String.valueOf(cnt));
             ps1.close();
      
             conn.close();
            }
            catch(Exception e1)
            {
                
            }
          try
            {
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
            if(conn!=null)
              System.out.println("Connection successful..");
            
            Statement ps1 = conn.createStatement();
                    
            
             
            ResultSet rs=ps1.executeQuery(" select ptname from product_type");
       
                    
            while(rs.next())
            {
      //        ptypecombo.addItem(rs.getString(1));
            }
             ps1.close();
      
             conn.close();
            }
            catch(Exception e1)
            {
                
            }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pidtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnametext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        contacttext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstext = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Patient ID");

        pidtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Patient Name");

        pnametext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Save ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Contact Number");

        contacttext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Address");

        addresstext.setColumns(20);
        addresstext.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        addresstext.setRows(5);
        jScrollPane1.setViewportView(addresstext);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setText("Take Appointment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(112, 112, 112)
                                            .addComponent(pidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(76, 76, 76)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(42, 42, 42)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(contacttext, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGap(163, 163, 163))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(153, 153, 153)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contacttext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
            boolean   contactresult= contacttext.getText().matches("[+-]?([0-9]*[.])?[0-9]+");
              if(pnametext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter patient name");
            }
            else if(addresstext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter address");
            }
               else if(contacttext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter contact number");
            }
                else if(contacttext.getText().length()!=10)
            {
                JOptionPane.showMessageDialog(this, "Please enter 10 digits in contact number");
            }
             else if(contactresult==false)
             {
              JOptionPane.showMessageDialog(this, "Please enter only digits in contact");   
 
             }
    
            else
            {
            PreparedStatement ps1 = conn.prepareStatement("update patient set pname=?,padd=?,pcontact=? where pid=?");
            int pno=Integer.parseInt(pidtext.getText());
            String pname=pnametext.getText();
            long contact=Long.parseLong(contacttext.getText());
              String address=addresstext.getText();
       
	 
             ps1.setString(1,pname);             
             ps1.setString(2,address);
             ps1.setLong(3,contact);
             
    //         ps1.setDouble(4,price);
      //       ps1.setInt(6,pno);
             ps1.executeUpdate();
             
         
             ps1.close();
             JOptionPane.showMessageDialog(this,"record updated");
             conn.close();
             new patient().setVisible(true);
             dispose();
            }
            }
            catch(Exception e1)
            {
                System.out.println("error"+e1.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
            PreparedStatement ps1 = conn.prepareStatement("delete from patient where pid=?");
             boolean   cidresult= pidtext.getText().matches("[0-9]");
              if(cidresult==false)
             {
              JOptionPane.showMessageDialog(this, "Please enter only digits in product ID");   
 
             }
            int pno=Integer.parseInt(pidtext.getText());
            
             
             ps1.setInt(1,pno);  
             
             int d=ps1.executeUpdate();
             if(d==0)
             {
               JOptionPane.showMessageDialog(this,"record not found");  
             }
             else
             {
               JOptionPane.showMessageDialog(this,"record deleted");  
               new patient().setVisible(true);
                dispose();
             }
             ps1.close();
             
             conn.close();
             
            }
            catch(Exception e1)
            {
                System.out.println("error"+e1.getMessage());
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
            PreparedStatement ps1 = conn.prepareStatement("select * from patient where pid=?");
            pno=Integer.parseInt(pidtext.getText());                 
	    
             ps1.setInt(1,pno);  
             
         
            ResultSet rs=ps1.executeQuery();
            if(!rs.isBeforeFirst() && rs.getRow() == 0)
            {
               JOptionPane.showMessageDialog(this,"record not found");
          
            }
            while(rs.next())
            {
                pnametext.setText(rs.getString("pname"));
                contacttext.setText(rs.getString("pcontact"));
                addresstext.setText(rs.getString("padd"));
             }
            }
            catch(Exception e1)
            {
                System.out.println("error"+e1.getMessage());
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
          boolean   contactresult= contacttext.getText().matches("[+-]?([0-9]*[.])?[0-9]+");
              if(pnametext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter patient name");
            }
            else if(addresstext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter address");
            }
               else if(contacttext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter contact number");
            }
                else if(contacttext.getText().length()!=10)
            {
                JOptionPane.showMessageDialog(this, "Please enter 10 digits in contact number");
            }
             else if(contactresult==false)
             {
              JOptionPane.showMessageDialog(this, "Please enter only digits in contact");   
 
             }
              
            else
            {
            PreparedStatement ps1 = conn.prepareStatement("insert into patient values(?,?,?,?)");
           pno=Integer.parseInt(pidtext.getText());
            String pname=pnametext.getText();
         //   double price=Double.parseDouble(pricetext.getText());
        //    double avaialble=Double.parseDouble(availableqtytext.getText());        
             
       
	     ps1.setInt(1,pno); 
             ps1.setString(2,pname);
             ps1.setString(3,addresstext.getText());
             ps1.setLong(4,Long.parseLong(contacttext.getText()));
          //   ps1.setDouble(5,price);             
          //   ps1.setDouble(6, avaialble);
            
             ps1.executeUpdate();
             
         
             ps1.close();
             JOptionPane.showMessageDialog(this,"record saved");
             conn.close();
             new patient().setVisible(true);
             dispose();
            }
            }
            catch(Exception e1)
            {
                System.out.println("error"+e1.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // int pid=Integer.parseInt(pidtext.getText());
         try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
            PreparedStatement ps1 = conn.prepareStatement("select * from patient where pid=?");
            pno=Integer.parseInt(pidtext.getText());                 
	    
             ps1.setInt(1,pno);  
             
         
            ResultSet rs=ps1.executeQuery();
            if(!rs.isBeforeFirst() && rs.getRow() == 0)
            {
               JOptionPane.showMessageDialog(this,"record not found...first enter patient detail ");          
            }
            else
            {
                new patientappointment(pno).setVisible(true);
                dispose();
            }
            }catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstext;
    private javax.swing.JTextField contacttext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pidtext;
    private javax.swing.JTextField pnametext;
    // End of variables declaration//GEN-END:variables
}
