/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.*;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author aarti
 */
public class patientappointment extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    int supid;
    int pid,did;
    public patientappointment(int pid) {
        initComponents();
        this.pid=pid;
        
        getContentPane().setBackground(Color.BLACK);
        for(int i=1;i<=24;i++)
        {
            hrcombo.addItem(String.valueOf(i));
        }
        int i=0;
        while(i<=60)
        {
            mincombo.addItem(String.valueOf(i));
            i=i+15;
        }
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
            Statement stmt = conn.createStatement();
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
            Statement ps1 = conn.createStatement();
                    
            
             
            ResultSet rs=ps1.executeQuery(" select max(apid) from appointment");
            int cnt=0;
            while(rs.next())
            {
              
                cnt=rs.getInt(1);
            }
            cnt++;
            pidtext.setText(String.valueOf(cnt));
             ps1.close();
      
             conn.close();
            }
            catch(Exception e1)
            {
                
            }
          try
            {
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
            if(conn!=null)
              System.out.println("Connection successful..");
            
            PreparedStatement ps1 = conn.prepareStatement("select pname from patient where pid=?");
               ps1.setInt(1,pid);       
            
             
            ResultSet rs=ps1.executeQuery();
          
                    
            while(rs.next())
            {
              pnametext.setText(rs.getString(1));
            }
                    
             Statement ps2 = conn.createStatement();
                    
            
             
            ResultSet rs1=ps2.executeQuery("select dname from doctor");
          
       while(rs1.next())
            {
              doccombo.addItem(rs1.getString(1));
            }
             ps1.close();
      
             conn.close();
            }
            catch(Exception e1)
            {
                  System.out.println(e1.getMessage());
            }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pidtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnametext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datecombo = new com.toedter.calendar.JDateChooser();
        mincombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        doccombo = new javax.swing.JComboBox<>();
        hrcombo = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Appointment ID");

        pidtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Time");

        pnametext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Doctor");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Patient Name");

        datecombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        mincombo.setEditable(true);
        mincombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mincombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select mins" }));
        mincombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mincomboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Date");

        doccombo.setEditable(true);
        doccombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doccombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor" }));
        doccombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                doccomboItemStateChanged(evt);
            }
        });

        hrcombo.setEditable(true);
        hrcombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hrcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hours" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doccombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(datecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnametext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hrcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mincombo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mincombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doccombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
           
        
            if(conn!=null)
              System.out.println("Connection successful..");
            
              if(pnametext.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter patient name");
            }
              else if(datecombo.getDate().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please Select date of appointment");
            }
              else if(hrcombo.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(this, "Please Select hrs of appointment");
            }
                  else if(mincombo.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(this, "Please Select mins of appointment");
            }
            else
            {
            PreparedStatement ps1 = conn.prepareStatement("insert into appointment values(?,?,?,?,?)");
            int pno=Integer.parseInt(pidtext.getText());
            String pname=pnametext.getText();
           Date bdate=datecombo.getDate();
             SimpleDateFormat bdate1 = new SimpleDateFormat("dd/MM/yyyy");  
             
             String bdate2=bdate1.format(bdate);        
         
          java.sql.Date sqlaDate = new java.sql.Date(bdate.getTime());
       
          String hr=(String)hrcombo.getSelectedItem();
           String min=(String)mincombo.getSelectedItem();
           String atime=hr+":"+min+":"+00;
           System.out.println(atime);
             System.out.println(java.sql.Time.valueOf(atime));
         //  JOptionPane.showMessageDialog(this,java.sql.Time.valueOf(atime));
	    
           PreparedStatement ps=conn.prepareStatement("select count(*) from appointment where adate=? and atime=? and doct_id=?");
           ps.setDate(1,sqlaDate);
           ps.setTime(2,java.sql.Time.valueOf(atime));
           ps.setInt(3, did);
           ResultSet rs1=ps.executeQuery();
           int cnt=0;
           while(rs1.next())
           {
               cnt=rs1.getInt(1);
           }
           if(cnt>0)
           {
                 JOptionPane.showMessageDialog(this,"Sorry...Appoinment is already booked");           
           }
           else
           {
           ps1.setInt(1,pno); 
             ps1.setDate(2,sqlaDate);
            ps1.setTime(3,java.sql.Time.valueOf(atime));
            ps1.setInt(4,did);
            ps1.setInt(5,pid);
            
             ps1.executeUpdate();
             
         
             ps1.close();
             JOptionPane.showMessageDialog(this,"appointment booked");
             conn.close();
             new appointmentreciept(Integer.parseInt(pidtext.getText())).setVisible(true);
             dispose();
                  }
            }
            }
            catch(Exception e1)
            {
                System.out.println("error"+e1.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mincomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mincomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mincomboActionPerformed

    private void doccomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_doccomboItemStateChanged
         String dname=(String)doccombo.getSelectedItem();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
             PreparedStatement ps1 = conn.prepareStatement("select doct_id from doctor where dname=?");
             ps1.setString(1,dname);
                    
            
            ResultSet rs=ps1.executeQuery();
  
            System.out.println(ps1);         
            while(rs.next())
            {
             did=rs.getInt(1);
            }
             ps1.close();             
             conn.close();
        }
        catch(Exception e)
        {
               
        }
    }//GEN-LAST:event_doccomboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           //     new patientappointment(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser datecombo;
    private javax.swing.JComboBox<String> doccombo;
    private javax.swing.JComboBox<String> hrcombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> mincombo;
    private javax.swing.JTextField pidtext;
    private javax.swing.JTextField pnametext;
    // End of variables declaration//GEN-END:variables
}
